In [313]:
import pandas as pd
import os

In [315]:
df_all_student = pd.read_csv("Student.csv",encoding ='utf-8')

In [316]:
df_all_student.shape

(10000, 13)

In [317]:
df_all_student.sample(5)

RowNumber  StudentId  StudentScore               School Gender  Age  \
6364       6365   10034546           368   Navodaya Vidyalaya    boy   11   
7569       7570   10017130           271   Navodaya Vidyalaya    boy    8   
3472       3473   10000276           676  Govt Primary School    boy    8   
8288       8289   10023221           803  Govt Primary School   girl    9   
5048       5049   10032888           794  Govt Primary School    boy    8   

      tenure  previousScore  sportsParticipated  Sibling  IsRegular  \
6364       2            933                   2        0          0   
7569       3            419                   0        1          0   
3472       3            322                   6        0          0   
8288       2            763                   6        0          0   
5048       3            283                   4        1          0   

      everFailed  IsFailed  
6364           1         1  
7569           0         0  
3472           0         1  
8288           0         0  
5048           1         1

In [318]:
X=df_all_student.iloc[:, 2:12]

In [319]:
y=df_all_student.iloc[:, 12]

In [320]:
from sklearn.preprocessing import LabelEncoder

In [321]:
labelencoder_X_School = LabelEncoder()
X.iloc[:,1]= labelencoder_X_School.fit_transform(X.iloc[:, 1])

In [322]:
labelencoder_X_Gender = LabelEncoder()
X.iloc[:,2]= labelencoder_X_Gender.fit_transform(X.iloc[:, 2])

In [323]:
X.head(3)

StudentScore  School  Gender  Age  tenure  previousScore  \
0           844       0       1   11       2            344   
1           230       2       1    7       2            918   
2           949       0       1   13       4            340   

   sportsParticipated  Sibling  IsRegular  everFailed  
0                   3        0          1           1  
1                   2        0          1           1  
2                   6        1          0           0

In [324]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [325]:
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()

C:\Users\vinjaisw0\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\vinjaisw0\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [326]:
pd.DataFrame(X,index=X[:,0]).head(2)

0    1    2      3    4     5    6      7    8    9    10   11
1.0  1.0  0.0  0.0  844.0  1.0  11.0  2.0  344.0  3.0  0.0  1.0  1.0
0.0  0.0  0.0  1.0  230.0  1.0   7.0  2.0  918.0  2.0  0.0  1.0  1.0

In [327]:
X = X[:, 1:]
pd.DataFrame(X,index=X[:,0]).head()

0    1      2    3     4    5      6    7    8    9    10
0.0  0.0  0.0  844.0  1.0  11.0  2.0  344.0  3.0  0.0  1.0  1.0
0.0  0.0  1.0  230.0  1.0   7.0  2.0  918.0  2.0  0.0  1.0  1.0
0.0  0.0  0.0  949.0  1.0  13.0  4.0  340.0  6.0  1.0  0.0  0.0
0.0  0.0  0.0  433.0  1.0  12.0  3.0  274.0  0.0  1.0  0.0  1.0
0.0  0.0  1.0  322.0  1.0   9.0  2.0  434.0  1.0  1.0  1.0  0.0

In [328]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [329]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [330]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

In [347]:
cf = Sequential()

In [348]:
cf.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
cf.add(Dropout(rate = 0.1))

In [349]:
cf.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
cf.add(Dropout(rate = 0.1))
cf.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [350]:
# from ann_visualizer.visualize import ann_viz;
# ann_viz(cf, title=" Simple ");

In [351]:
cf.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [352]:
X_train.shape

(8000, 11)

In [353]:
cf.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 3s 365us/step - loss: 0.6932 - accuracy: 0.4978
Epoch 2/100
8000/8000 [==============================] - 2s 229us/step - loss: 0.6932 - accuracy: 0.4994
Epoch 3/100
8000/8000 [==============================] - 2s 230us/step - loss: 0.6932 - accuracy: 0.4922
Epoch 4/100
8000/8000 [==============================] - 2s 234us/step - loss: 0.6932 - accuracy: 0.4994
Epoch 5/100
8000/8000 [==============================] - 2s 236us/step - loss: 0.6931 - accuracy: 0.4983
Epoch 6/100
8000/8000 [==============================] - 2s 217us/step - loss: 0.6929 - accuracy: 0.5173
Epoch 7/100
8000/8000 [==============================] - 2s 246us/step - loss: 0.6924 - accuracy: 0.5113
Epoch 8/100
8000/8000 [==============================] - 2s 246us/step - loss: 0.6925 - accuracy: 0.5186
Epoch 9/100
8000/8000 [==============================] - 2s 256us/step - loss: 0.6925 - accuracy: 0.5197
Epoch 10/100
8000/8000 [==============================]

In [354]:
y_prediction =cf.predict(X_test)

In [364]:
X_test

array([[ 1.75486502, -0.57369368,  0.32535301, ..., -1.002002  ,
        -0.98117712,  0.99178375],
       [-0.5698444 , -0.57369368, -0.73241421, ...,  0.998002  ,
        -0.98117712,  0.99178375],
       [-0.5698444 ,  1.74309049, -0.69355746, ..., -1.002002  ,
        -0.98117712, -1.00828431],
       ...,
       [-0.5698444 ,  1.74309049,  0.66642897, ...,  0.998002  ,
        -0.98117712,  0.99178375],
       [ 1.75486502, -0.57369368, -0.24022865, ...,  0.998002  ,
        -0.98117712,  0.99178375],
       [ 1.75486502, -0.57369368,  0.86503016, ..., -1.002002  ,
        -0.98117712, -1.00828431]])

In [374]:
X_test[0:2,:]

array([[ 1.75486502, -0.57369368,  0.32535301,  1.09168714,  0.79424936,
        -0.00459255,  0.59821525, -0.64097409, -1.002002  , -0.98117712,
         0.99178375],
       [-0.5698444 , -0.57369368, -0.73241421,  1.09168714,  1.18041655,
        -1.2292738 ,  1.4695826 ,  1.53421584,  0.998002  , -0.98117712,
         0.99178375]])

In [376]:
cf.predict(X_test[0:1,:])

array([[0.46952206]], dtype=float32)

In [373]:
# pd.DataFrame(y_prediction,index=y_prediction[:,0]).head()

In [ ]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
def kera_classifier():
    cf = Sequential()
    cf.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    cf.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    cf.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    cf.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return cf
cf = KerasClassifier(build_fn = kera_classifier, batch_size = 10, epochs = 100)
accuracies = cross_val_score(estimator = cf, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()

In [ ]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
def kera_classifier(optimizer):
    cf = Sequential()
    cf.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    cf.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    cf.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    cf.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return cf
cf = KerasClassifier(build_fn = kera_classifier)
parameters = {'batch_size': [10, 15],
              'epochs': [10, 50],
              'optimizer': ['adam', 'rmsprop']}
gv_search = GridSearchCV(estimator = cf,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10)
gv_search = gv_search.fit(X_train, y_train)
best_param = gv_search.best_params_
best_acc = gv_search.best_score_